version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: meu-mongo-java
    ports:
      - "27017:27017"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: meu-elastic-java
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"